Requirement already satisfied: statsmodels in ./.conda/envs/Tesis3/lib/python3.9/site-packages (0.14.2)
Requirement already satisfied: numpy>=1.22.3 in ./.local/lib/python3.9/site-packages (from statsmodels) (1.23.0)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in ./.local/lib/python3.9/site-packages (from statsmodels) (1.8.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from statsmodels) (0.5.6)
Requirement already satisfied: packaging>=21.3 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from statsmodels) (24.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: six in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from patsy>=0.5.6->statsmodels) (1.16.0)
Requirement already satisfied: pyyaml in ./.conda/envs/Tesis3/lib/python3.9/site-packages (6.0.1)
Requirement already satisfied: scikit-learn in ./.conda/envs/Tesis3/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in ./.local/lib/python3.9/site-packages (from scikit-learn) (1.23.0)
Requirement already satisfied: scipy>=1.6.0 in ./.local/lib/python3.9/site-packages (from scikit-learn) (1.8.0)
Requirement already satisfied: joblib>=1.2.0 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.conda/envs/Tesis3/lib/python3.9/site-packages (from scikit-learn) (3.5.0)
Soy un JOB de prueba
Corri en la maquina: nodea-6
Corri el: nodea-6
Ejecutando Script de python 

WARNING: File may have been truncated: actual file length (2554920960) is smaller than the expected size (2621206080) [astropy.io.fits.file]
importe las liberias
Filename: Medias-Desviacion278.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()      
  1  MEDIAS        1 ImageHDU         7   (1260548,)   float64   
  2  MAD           1 ImageHDU         7   (1260548,)   float64   
  3  KS_NSAT       1 ImageHDU         8   (66, 1202504)   float64   
  4  EKS_NSAT      1 ImageHDU         8   (66, 1202504)   float64   
  5  MEDIASNS      1 ImageHDU         7   (1202504,)   float64   
  6  MADNS         1 ImageHDU         7   (1202504,)   float64   
  7  Q3_KS         1 ImageHDU         8   (66, 933459)   float64   
  8  Q3_EKS        1 ImageHDU         8   (66, 933459)   float64   
  9  D3_KS         1 ImageHDU         8   (66, 308874)   float64   
 10  D3_EKS        1 ImageHDU         8   (66, 308874)   float64   
Filename: Medias-Desviacion279.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()      
  1  MEDIAS        1 ImageHDU         7   (1280954,)   float64   
  2  MAD           1 ImageHDU         7   (1280954,)   float64   
  3  KS_NSAT       1 ImageHDU         8   (68, 1223069)   float64   
  4  EKS_NSAT      1 ImageHDU         8   (68, 1223069)   float64   
  5  MEDIASNS      1 ImageHDU         7   (1223069,)   float64   
  6  MADNS         1 ImageHDU         7   (1223069,)   float64   
  7  Q3_EKS        1 ImageHDU         8   (68, 956867)   float64   
  8  Q3_KS         1 ImageHDU         8   (68, 956867)   float64   
  9  EQ3_EKS       1 ImageHDU         8   (68, 956867)   float64   
 10  D3_KS         1 ImageHDU         8   (68, 306755)   float64   
 11  ED3_EKS       1 ImageHDU         8   (68, 306755)   float64   
615629
<class 'numpy.ndarray'>
615629
<class 'numpy.ndarray'>
615629
<class 'numpy.ndarray'>
615629
<class 'numpy.ndarray'>
615629
<class 'list'>
615629
<class 'numpy.ndarray'>
615629
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[-1.3688615134808233 0.5008095482954577 1.1046563569528989 ...
 -0.2718929167449089 0.08638161412846414 -0.22839380151745758]
[0.019273799999999855 0.022238999999999527 0.0504083999999984 ...
 0.013343400000000508 0.010378200000002146 0.010378199999999518]
[0.3159606029249723 -0.3948481633337821 -0.02212284036931695 ...
 1.511767001785741 -0.29289898924376934 -1.1039709363394028]
[1.0375533939638817 1.1318155235924148 1.131809207141025 ...
 -1.3948715247926964 -1.3739778591487821 -1.0287376077216983]
[0.3169580678379597 0.30190491485783033 0.319625145405303 ... 0.0 0.0 0.0]
[-0.22355984086361752 0.26618982971181243 2.6063652059450497 ... 0.0 0.0
 0.0]
[1.0375533939638817 1.1318155235924148 1.131809207141025 ...
 -1.3948715247926964 -1.3739778591487821 -1.0287376077216983]
No hay str
<class 'numpy.ndarray'>
llegue a prediccion
Traceback (most recent call last):
  File "/hpcfs/home/fisica/c.cardenasu/Validacion_RamdomF7879.py", line 411, in <module>
    predictions = model.predict(matrix)
AttributeError: 'str' object has no attribute 'predict'
Finalice la ejecucion del script 

